/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as R403RouteImport } from './routes/403'
import { Route as CrosshairGeneratorRouteImport } from './routes/crosshair-generator'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DeadlockModsNotWorkingRouteImport } from './routes/deadlock-mods-not-working'
import { Route as DiscordRouteImport } from './routes/discord'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as HowToInstallDeadlockModsRouteImport } from './routes/how-to-install-deadlock-mods'
import { Route as KvParserRouteImport } from './routes/kv-parser'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ModsRouteImport } from './routes/mods'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RandomizerRouteImport } from './routes/randomizer'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SkinsRouteImport } from './routes/skins'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as VpkAnalyzerRouteImport } from './routes/vpk-analyzer'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as CompareGrimoireRouteImport } from './routes/compare/grimoire'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAnnouncementsRouteImport } from './routes/dashboard/announcements'
import { Route as DownloadIndexRouteImport } from './routes/download/index'
import { Route as DownloadLinuxRouteImport } from './routes/download/linux'
import { Route as DownloadWindowsRouteImport } from './routes/download/windows'
import { Route as ModIdRouteImport } from './routes/mod/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const CrosshairGeneratorRoute = CrosshairGeneratorRouteImport.update({
  id: '/crosshair-generator',
  path: '/crosshair-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeadlockModsNotWorkingRoute = DeadlockModsNotWorkingRouteImport.update({
  id: '/deadlock-mods-not-working',
  path: '/deadlock-mods-not-working',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordRoute = DiscordRouteImport.update({
  id: '/discord',
  path: '/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToInstallDeadlockModsRoute =
  HowToInstallDeadlockModsRouteImport.update({
    id: '/how-to-install-deadlock-mods',
    path: '/how-to-install-deadlock-mods',
    getParentRoute: () => rootRouteImport,
  } as any)
const KvParserRoute = KvParserRouteImport.update({
  id: '/kv-parser',
  path: '/kv-parser',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModsRoute = ModsRouteImport.update({
  id: '/mods',
  path: '/mods',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomizerRoute = RandomizerRouteImport.update({
  id: '/randomizer',
  path: '/randomizer',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SkinsRoute = SkinsRouteImport.update({
  id: '/skins',
  path: '/skins',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const VpkAnalyzerRoute = VpkAnalyzerRouteImport.update({
  id: '/vpk-analyzer',
  path: '/vpk-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareGrimoireRoute = CompareGrimoireRouteImport.update({
  id: '/compare/grimoire',
  path: '/compare/grimoire',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnnouncementsRoute = DashboardAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => DashboardRoute,
} as any)
const DownloadIndexRoute = DownloadIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DownloadRoute,
} as any)
const DownloadLinuxRoute = DownloadLinuxRouteImport.update({
  id: '/linux',
  path: '/linux',
  getParentRoute: () => DownloadRoute,
} as any)
const DownloadWindowsRoute = DownloadWindowsRouteImport.update({
  id: '/windows',
  path: '/windows',
  getParentRoute: () => DownloadRoute,
} as any)
const ModIdRoute = ModIdRouteImport.update({
  id: '/mod/$id',
  path: '/mod/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/403': typeof R403Route
  '/crosshair-generator': typeof CrosshairGeneratorRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/deadlock-mods-not-working': typeof DeadlockModsNotWorkingRoute
  '/discord': typeof DiscordRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRouteWithChildren
  '/how-to-install-deadlock-mods': typeof HowToInstallDeadlockModsRoute
  '/kv-parser': typeof KvParserRoute
  '/login': typeof LoginRoute
  '/mods': typeof ModsRoute
  '/privacy': typeof PrivacyRoute
  '/randomizer': typeof RandomizerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skins': typeof SkinsRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/transparency': typeof TransparencyRoute
  '/vpk-analyzer': typeof VpkAnalyzerRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/compare/grimoire': typeof CompareGrimoireRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/download/linux': typeof DownloadLinuxRoute
  '/download/windows': typeof DownloadWindowsRoute
  '/mod/$id': typeof ModIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/download/': typeof DownloadIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/403': typeof R403Route
  '/crosshair-generator': typeof CrosshairGeneratorRoute
  '/deadlock-mods-not-working': typeof DeadlockModsNotWorkingRoute
  '/discord': typeof DiscordRoute
  '/docs': typeof DocsRoute
  '/how-to-install-deadlock-mods': typeof HowToInstallDeadlockModsRoute
  '/kv-parser': typeof KvParserRoute
  '/login': typeof LoginRoute
  '/mods': typeof ModsRoute
  '/privacy': typeof PrivacyRoute
  '/randomizer': typeof RandomizerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skins': typeof SkinsRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/transparency': typeof TransparencyRoute
  '/vpk-analyzer': typeof VpkAnalyzerRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/compare/grimoire': typeof CompareGrimoireRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/download/linux': typeof DownloadLinuxRoute
  '/download/windows': typeof DownloadWindowsRoute
  '/mod/$id': typeof ModIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/download': typeof DownloadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/403': typeof R403Route
  '/crosshair-generator': typeof CrosshairGeneratorRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/deadlock-mods-not-working': typeof DeadlockModsNotWorkingRoute
  '/discord': typeof DiscordRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRouteWithChildren
  '/how-to-install-deadlock-mods': typeof HowToInstallDeadlockModsRoute
  '/kv-parser': typeof KvParserRoute
  '/login': typeof LoginRoute
  '/mods': typeof ModsRoute
  '/privacy': typeof PrivacyRoute
  '/randomizer': typeof RandomizerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skins': typeof SkinsRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/transparency': typeof TransparencyRoute
  '/vpk-analyzer': typeof VpkAnalyzerRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/compare/grimoire': typeof CompareGrimoireRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/download/linux': typeof DownloadLinuxRoute
  '/download/windows': typeof DownloadWindowsRoute
  '/mod/$id': typeof ModIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/download/': typeof DownloadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/403'
    | '/crosshair-generator'
    | '/dashboard'
    | '/deadlock-mods-not-working'
    | '/discord'
    | '/docs'
    | '/download'
    | '/how-to-install-deadlock-mods'
    | '/kv-parser'
    | '/login'
    | '/mods'
    | '/privacy'
    | '/randomizer'
    | '/sitemap.xml'
    | '/skins'
    | '/status'
    | '/terms'
    | '/transparency'
    | '/vpk-analyzer'
    | '/auth/callback'
    | '/compare/grimoire'
    | '/dashboard/announcements'
    | '/download/linux'
    | '/download/windows'
    | '/mod/$id'
    | '/dashboard/'
    | '/download/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/403'
    | '/crosshair-generator'
    | '/deadlock-mods-not-working'
    | '/discord'
    | '/docs'
    | '/how-to-install-deadlock-mods'
    | '/kv-parser'
    | '/login'
    | '/mods'
    | '/privacy'
    | '/randomizer'
    | '/sitemap.xml'
    | '/skins'
    | '/status'
    | '/terms'
    | '/transparency'
    | '/vpk-analyzer'
    | '/auth/callback'
    | '/compare/grimoire'
    | '/dashboard/announcements'
    | '/download/linux'
    | '/download/windows'
    | '/mod/$id'
    | '/dashboard'
    | '/download'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/403'
    | '/crosshair-generator'
    | '/dashboard'
    | '/deadlock-mods-not-working'
    | '/discord'
    | '/docs'
    | '/download'
    | '/how-to-install-deadlock-mods'
    | '/kv-parser'
    | '/login'
    | '/mods'
    | '/privacy'
    | '/randomizer'
    | '/sitemap.xml'
    | '/skins'
    | '/status'
    | '/terms'
    | '/transparency'
    | '/vpk-analyzer'
    | '/auth/callback'
    | '/compare/grimoire'
    | '/dashboard/announcements'
    | '/download/linux'
    | '/download/windows'
    | '/mod/$id'
    | '/dashboard/'
    | '/download/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  R403Route: typeof R403Route
  CrosshairGeneratorRoute: typeof CrosshairGeneratorRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DeadlockModsNotWorkingRoute: typeof DeadlockModsNotWorkingRoute
  DiscordRoute: typeof DiscordRoute
  DocsRoute: typeof DocsRoute
  DownloadRoute: typeof DownloadRouteWithChildren
  HowToInstallDeadlockModsRoute: typeof HowToInstallDeadlockModsRoute
  KvParserRoute: typeof KvParserRoute
  LoginRoute: typeof LoginRoute
  ModsRoute: typeof ModsRoute
  PrivacyRoute: typeof PrivacyRoute
  RandomizerRoute: typeof RandomizerRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SkinsRoute: typeof SkinsRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
  TransparencyRoute: typeof TransparencyRoute
  VpkAnalyzerRoute: typeof VpkAnalyzerRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CompareGrimoireRoute: typeof CompareGrimoireRoute
  ModIdRoute: typeof ModIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crosshair-generator': {
      id: '/crosshair-generator'
      path: '/crosshair-generator'
      fullPath: '/crosshair-generator'
      preLoaderRoute: typeof CrosshairGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deadlock-mods-not-working': {
      id: '/deadlock-mods-not-working'
      path: '/deadlock-mods-not-working'
      fullPath: '/deadlock-mods-not-working'
      preLoaderRoute: typeof DeadlockModsNotWorkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord': {
      id: '/discord'
      path: '/discord'
      fullPath: '/discord'
      preLoaderRoute: typeof DiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-install-deadlock-mods': {
      id: '/how-to-install-deadlock-mods'
      path: '/how-to-install-deadlock-mods'
      fullPath: '/how-to-install-deadlock-mods'
      preLoaderRoute: typeof HowToInstallDeadlockModsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kv-parser': {
      id: '/kv-parser'
      path: '/kv-parser'
      fullPath: '/kv-parser'
      preLoaderRoute: typeof KvParserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mods': {
      id: '/mods'
      path: '/mods'
      fullPath: '/mods'
      preLoaderRoute: typeof ModsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/randomizer': {
      id: '/randomizer'
      path: '/randomizer'
      fullPath: '/randomizer'
      preLoaderRoute: typeof RandomizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skins': {
      id: '/skins'
      path: '/skins'
      fullPath: '/skins'
      preLoaderRoute: typeof SkinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vpk-analyzer': {
      id: '/vpk-analyzer'
      path: '/vpk-analyzer'
      fullPath: '/vpk-analyzer'
      preLoaderRoute: typeof VpkAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/grimoire': {
      id: '/compare/grimoire'
      path: '/compare/grimoire'
      fullPath: '/compare/grimoire'
      preLoaderRoute: typeof CompareGrimoireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/announcements': {
      id: '/dashboard/announcements'
      path: '/announcements'
      fullPath: '/dashboard/announcements'
      preLoaderRoute: typeof DashboardAnnouncementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/download/': {
      id: '/download/'
      path: '/'
      fullPath: '/download/'
      preLoaderRoute: typeof DownloadIndexRouteImport
      parentRoute: typeof DownloadRoute
    }
    '/download/linux': {
      id: '/download/linux'
      path: '/linux'
      fullPath: '/download/linux'
      preLoaderRoute: typeof DownloadLinuxRouteImport
      parentRoute: typeof DownloadRoute
    }
    '/download/windows': {
      id: '/download/windows'
      path: '/windows'
      fullPath: '/download/windows'
      preLoaderRoute: typeof DownloadWindowsRouteImport
      parentRoute: typeof DownloadRoute
    }
    '/mod/$id': {
      id: '/mod/$id'
      path: '/mod/$id'
      fullPath: '/mod/$id'
      preLoaderRoute: typeof ModIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnnouncementsRoute: typeof DashboardAnnouncementsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnnouncementsRoute: DashboardAnnouncementsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DownloadRouteChildren {
  DownloadLinuxRoute: typeof DownloadLinuxRoute
  DownloadWindowsRoute: typeof DownloadWindowsRoute
  DownloadIndexRoute: typeof DownloadIndexRoute
}

const DownloadRouteChildren: DownloadRouteChildren = {
  DownloadLinuxRoute: DownloadLinuxRoute,
  DownloadWindowsRoute: DownloadWindowsRoute,
  DownloadIndexRoute: DownloadIndexRoute,
}

const DownloadRouteWithChildren = DownloadRoute._addFileChildren(
  DownloadRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  R403Route: R403Route,
  CrosshairGeneratorRoute: CrosshairGeneratorRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DeadlockModsNotWorkingRoute: DeadlockModsNotWorkingRoute,
  DiscordRoute: DiscordRoute,
  DocsRoute: DocsRoute,
  DownloadRoute: DownloadRouteWithChildren,
  HowToInstallDeadlockModsRoute: HowToInstallDeadlockModsRoute,
  KvParserRoute: KvParserRoute,
  LoginRoute: LoginRoute,
  ModsRoute: ModsRoute,
  PrivacyRoute: PrivacyRoute,
  RandomizerRoute: RandomizerRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SkinsRoute: SkinsRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
  TransparencyRoute: TransparencyRoute,
  VpkAnalyzerRoute: VpkAnalyzerRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CompareGrimoireRoute: CompareGrimoireRoute,
  ModIdRoute: ModIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
