/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VpkAnalyzerRouteImport } from './routes/vpk-analyzer'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SitemapModsDotxmlRouteImport } from './routes/sitemap-mods[.]xml'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KvParserRouteImport } from './routes/kv-parser'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DiscordRouteImport } from './routes/discord'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CrosshairGeneratorRouteImport } from './routes/crosshair-generator'
import { Route as R403RouteImport } from './routes/403'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModsIndexRouteImport } from './routes/mods/index'
import { Route as DownloadIndexRouteImport } from './routes/download/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ModIdRouteImport } from './routes/mod/$id'
import { Route as DownloadWindowsRouteImport } from './routes/download/windows'
import { Route as DownloadLinuxRouteImport } from './routes/download/linux'
import { Route as DashboardAnnouncementsRouteImport } from './routes/dashboard/announcements'
import { Route as AuthDesktopCallbackRouteImport } from './routes/auth/desktop-callback'

const VpkAnalyzerRoute = VpkAnalyzerRouteImport.update({
  id: '/vpk-analyzer',
  path: '/vpk-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapModsDotxmlRoute = SitemapModsDotxmlRouteImport.update({
  id: '/sitemap-mods.xml',
  path: '/sitemap-mods.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KvParserRoute = KvParserRouteImport.update({
  id: '/kv-parser',
  path: '/kv-parser',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordRoute = DiscordRouteImport.update({
  id: '/discord',
  path: '/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrosshairGeneratorRoute = CrosshairGeneratorRouteImport.update({
  id: '/crosshair-generator',
  path: '/crosshair-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModsIndexRoute = ModsIndexRouteImport.update({
  id: '/mods/',
  path: '/mods/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadIndexRoute = DownloadIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DownloadRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ModIdRoute = ModIdRouteImport.update({
  id: '/mod/$id',
  path: '/mod/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadWindowsRoute = DownloadWindowsRouteImport.update({
  id: '/windows',
  path: '/windows',
  getParentRoute: () => DownloadRoute,
} as any)
const DownloadLinuxRoute = DownloadLinuxRouteImport.update({
  id: '/linux',
  path: '/linux',
  getParentRoute: () => DownloadRoute,
} as any)
const DashboardAnnouncementsRoute = DashboardAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthDesktopCallbackRoute = AuthDesktopCallbackRouteImport.update({
  id: '/auth/desktop-callback',
  path: '/auth/desktop-callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/403': typeof R403Route
  '/crosshair-generator': typeof CrosshairGeneratorRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/discord': typeof DiscordRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRouteWithChildren
  '/friends': typeof FriendsRoute
  '/kv-parser': typeof KvParserRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/sitemap-mods.xml': typeof SitemapModsDotxmlRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/vpk-analyzer': typeof VpkAnalyzerRoute
  '/auth/desktop-callback': typeof AuthDesktopCallbackRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/download/linux': typeof DownloadLinuxRoute
  '/download/windows': typeof DownloadWindowsRoute
  '/mod/$id': typeof ModIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/download/': typeof DownloadIndexRoute
  '/mods': typeof ModsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/403': typeof R403Route
  '/crosshair-generator': typeof CrosshairGeneratorRoute
  '/discord': typeof DiscordRoute
  '/docs': typeof DocsRoute
  '/friends': typeof FriendsRoute
  '/kv-parser': typeof KvParserRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/sitemap-mods.xml': typeof SitemapModsDotxmlRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/vpk-analyzer': typeof VpkAnalyzerRoute
  '/auth/desktop-callback': typeof AuthDesktopCallbackRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/download/linux': typeof DownloadLinuxRoute
  '/download/windows': typeof DownloadWindowsRoute
  '/mod/$id': typeof ModIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/download': typeof DownloadIndexRoute
  '/mods': typeof ModsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/403': typeof R403Route
  '/crosshair-generator': typeof CrosshairGeneratorRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/discord': typeof DiscordRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRouteWithChildren
  '/friends': typeof FriendsRoute
  '/kv-parser': typeof KvParserRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/sitemap-mods.xml': typeof SitemapModsDotxmlRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/vpk-analyzer': typeof VpkAnalyzerRoute
  '/auth/desktop-callback': typeof AuthDesktopCallbackRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/download/linux': typeof DownloadLinuxRoute
  '/download/windows': typeof DownloadWindowsRoute
  '/mod/$id': typeof ModIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/download/': typeof DownloadIndexRoute
  '/mods/': typeof ModsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/403'
    | '/crosshair-generator'
    | '/dashboard'
    | '/discord'
    | '/docs'
    | '/download'
    | '/friends'
    | '/kv-parser'
    | '/login'
    | '/privacy'
    | '/register'
    | '/sitemap-mods.xml'
    | '/status'
    | '/terms'
    | '/vpk-analyzer'
    | '/auth/desktop-callback'
    | '/dashboard/announcements'
    | '/download/linux'
    | '/download/windows'
    | '/mod/$id'
    | '/dashboard/'
    | '/download/'
    | '/mods'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/403'
    | '/crosshair-generator'
    | '/discord'
    | '/docs'
    | '/friends'
    | '/kv-parser'
    | '/login'
    | '/privacy'
    | '/register'
    | '/sitemap-mods.xml'
    | '/status'
    | '/terms'
    | '/vpk-analyzer'
    | '/auth/desktop-callback'
    | '/dashboard/announcements'
    | '/download/linux'
    | '/download/windows'
    | '/mod/$id'
    | '/dashboard'
    | '/download'
    | '/mods'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/403'
    | '/crosshair-generator'
    | '/dashboard'
    | '/discord'
    | '/docs'
    | '/download'
    | '/friends'
    | '/kv-parser'
    | '/login'
    | '/privacy'
    | '/register'
    | '/sitemap-mods.xml'
    | '/status'
    | '/terms'
    | '/vpk-analyzer'
    | '/auth/desktop-callback'
    | '/dashboard/announcements'
    | '/download/linux'
    | '/download/windows'
    | '/mod/$id'
    | '/dashboard/'
    | '/download/'
    | '/mods/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  R403Route: typeof R403Route
  CrosshairGeneratorRoute: typeof CrosshairGeneratorRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DiscordRoute: typeof DiscordRoute
  DocsRoute: typeof DocsRoute
  DownloadRoute: typeof DownloadRouteWithChildren
  FriendsRoute: typeof FriendsRoute
  KvParserRoute: typeof KvParserRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  SitemapModsDotxmlRoute: typeof SitemapModsDotxmlRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
  VpkAnalyzerRoute: typeof VpkAnalyzerRoute
  AuthDesktopCallbackRoute: typeof AuthDesktopCallbackRoute
  ModIdRoute: typeof ModIdRoute
  ModsIndexRoute: typeof ModsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vpk-analyzer': {
      id: '/vpk-analyzer'
      path: '/vpk-analyzer'
      fullPath: '/vpk-analyzer'
      preLoaderRoute: typeof VpkAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-mods.xml': {
      id: '/sitemap-mods.xml'
      path: '/sitemap-mods.xml'
      fullPath: '/sitemap-mods.xml'
      preLoaderRoute: typeof SitemapModsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kv-parser': {
      id: '/kv-parser'
      path: '/kv-parser'
      fullPath: '/kv-parser'
      preLoaderRoute: typeof KvParserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord': {
      id: '/discord'
      path: '/discord'
      fullPath: '/discord'
      preLoaderRoute: typeof DiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crosshair-generator': {
      id: '/crosshair-generator'
      path: '/crosshair-generator'
      fullPath: '/crosshair-generator'
      preLoaderRoute: typeof CrosshairGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mods/': {
      id: '/mods/'
      path: '/mods'
      fullPath: '/mods'
      preLoaderRoute: typeof ModsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/': {
      id: '/download/'
      path: '/'
      fullPath: '/download/'
      preLoaderRoute: typeof DownloadIndexRouteImport
      parentRoute: typeof DownloadRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/mod/$id': {
      id: '/mod/$id'
      path: '/mod/$id'
      fullPath: '/mod/$id'
      preLoaderRoute: typeof ModIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/windows': {
      id: '/download/windows'
      path: '/windows'
      fullPath: '/download/windows'
      preLoaderRoute: typeof DownloadWindowsRouteImport
      parentRoute: typeof DownloadRoute
    }
    '/download/linux': {
      id: '/download/linux'
      path: '/linux'
      fullPath: '/download/linux'
      preLoaderRoute: typeof DownloadLinuxRouteImport
      parentRoute: typeof DownloadRoute
    }
    '/dashboard/announcements': {
      id: '/dashboard/announcements'
      path: '/announcements'
      fullPath: '/dashboard/announcements'
      preLoaderRoute: typeof DashboardAnnouncementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/desktop-callback': {
      id: '/auth/desktop-callback'
      path: '/auth/desktop-callback'
      fullPath: '/auth/desktop-callback'
      preLoaderRoute: typeof AuthDesktopCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnnouncementsRoute: typeof DashboardAnnouncementsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnnouncementsRoute: DashboardAnnouncementsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DownloadRouteChildren {
  DownloadLinuxRoute: typeof DownloadLinuxRoute
  DownloadWindowsRoute: typeof DownloadWindowsRoute
  DownloadIndexRoute: typeof DownloadIndexRoute
}

const DownloadRouteChildren: DownloadRouteChildren = {
  DownloadLinuxRoute: DownloadLinuxRoute,
  DownloadWindowsRoute: DownloadWindowsRoute,
  DownloadIndexRoute: DownloadIndexRoute,
}

const DownloadRouteWithChildren = DownloadRoute._addFileChildren(
  DownloadRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  R403Route: R403Route,
  CrosshairGeneratorRoute: CrosshairGeneratorRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DiscordRoute: DiscordRoute,
  DocsRoute: DocsRoute,
  DownloadRoute: DownloadRouteWithChildren,
  FriendsRoute: FriendsRoute,
  KvParserRoute: KvParserRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  SitemapModsDotxmlRoute: SitemapModsDotxmlRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
  VpkAnalyzerRoute: VpkAnalyzerRoute,
  AuthDesktopCallbackRoute: AuthDesktopCallbackRoute,
  ModIdRoute: ModIdRoute,
  ModsIndexRoute: ModsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
