// Generated from packages/shared/src/heroes/.
// Run apps/desktop/scripts/generate-gamebanana-hero-registry.ts after edits.

pub const HERO_ALIASES: &[(&str, &[&str])] = &[
  (
    "Abrams",
    &["Abrams", "atlas", "atlas detective", "atlas detective v2"],
  ),
  ("Apollo", &["Apollo", "fencer"]),
  ("Bebop", &["Bebop"]),
  ("Billy", &["Billy", "punkgoat"]),
  ("Calico", &["Calico", "cadence", "nano"]),
  ("Celeste", &["Celeste", "unicorn"]),
  ("Doorman", &["Doorman", "doorman v2"]),
  ("Drifter", &["Drifter"]),
  ("Dynamo", &["Dynamo", "prof dynamo"]),
  ("Graves", &["Graves", "necro"]),
  (
    "Grey Talon",
    &[
      "Grey Talon",
      "GreyTalon",
      "archer",
      "archer v2",
      "greytalon",
    ],
  ),
  ("Haze", &["Haze", "haze v2"]),
  ("Holliday", &["Holliday", "astro"]),
  ("Infernus", &["Infernus", "inferno", "inferno v4"]),
  ("Ivy", &["Ivy", "tengu"]),
  ("Kelvin", &["Kelvin", "kelvin explorer", "kelvin v2"]),
  (
    "Lady Geist",
    &["Lady Geist", "LadyGeist", "geist", "ghost", "ladygeist"],
  ),
  ("Lash", &["Lash", "lash v2"]),
  ("McGinnis", &["McGinnis", "engineer"]),
  ("Mina", &["Mina", "vampirebat"]),
  ("Mirage", &["Mirage", "mirage v2"]),
  (
    "Mo & Krill",
    &["Mo & Krill", "MoKrill", "digger", "mo krill", "mokrill"],
  ),
  ("Paige", &["Paige", "bookworm"]),
  ("Paradox", &["Paradox", "chrono"]),
  ("Pocket", &["Pocket", "synth"]),
  ("Rem", &["Rem", "familiar"]),
  ("Seven", &["Seven", "7", "gigawatt", "gigawatt prisoner"]),
  ("Shiv", &["Shiv", "shiv ult"]),
  ("Silver", &["Silver", "werewolf"]),
  ("Sinclair", &["Sinclair", "magician", "magician v2"]),
  ("Venator", &["Venator", "priest"]),
  ("Victor", &["Victor", "frank", "frank v2", "viktor"]),
  ("Vindicta", &["Vindicta", "hornet", "hornet v3"]),
  ("Viscous", &["Viscous"]),
  ("Vyper", &["Vyper", "viper"]),
  ("Warden", &["Warden"]),
  (
    "Wraith",
    &[
      "Wraith",
      "wraith gen man",
      "wraith magician",
      "wraith puppeteer",
    ],
  ),
  ("Wrecker", &["Wrecker", "butcher"]),
  ("Yamato", &["Yamato", "yamato v2"]),
];

pub const HERO_FUZZY_TOKENS: &[(&str, &[&str])] = &[
  ("Abrams", &["brams"]),
  ("Grey Talon", &["talon"]),
  ("Infernus", &["fernus"]),
  ("Lady Geist", &["geist", "gaist"]),
  ("Mo & Krill", &["krill"]),
  ("Paradox", &["dox"]),
];

pub const HERO_PHRASES: &[(&str, &[&str])] = &[
  ("Abrams", &["atlas detective", "atlas detective v2"]),
  ("Doorman", &["doorman v2"]),
  ("Dynamo", &["prof dynamo"]),
  ("Grey Talon", &["grey talon", "archer v2"]),
  ("Haze", &["haze v2"]),
  ("Infernus", &["inferno v4"]),
  ("Kelvin", &["kelvin explorer", "kelvin v2"]),
  ("Lady Geist", &["lady geist", "lady geist"]),
  ("Lash", &["lash v2"]),
  ("Mirage", &["mirage v2"]),
  (
    "Mo & Krill",
    &["mo krill", "mo and krill", "mo krill", "mo krill"],
  ),
  ("Seven", &["gigawatt prisoner"]),
  ("Shiv", &["shiv ult"]),
  ("Sinclair", &["magician v2"]),
  ("Victor", &["frank v2"]),
  ("Vindicta", &["hornet v3"]),
  (
    "Wraith",
    &["wraith gen man", "wraith magician", "wraith puppeteer"],
  ),
  ("Yamato", &["yamato v2"]),
];
