/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AuthDesktopCallbackRouteImport } from "./routes/auth/desktop-callback";
import { Route as LoginRouteImport } from "./routes/login";

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthDesktopCallbackRoute = AuthDesktopCallbackRouteImport.update({
  id: "/auth/desktop-callback",
  path: "/auth/desktop-callback",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/login": typeof LoginRoute;
  "/auth/desktop-callback": typeof AuthDesktopCallbackRoute;
}
export interface FileRoutesByTo {
  "/login": typeof LoginRoute;
  "/auth/desktop-callback": typeof AuthDesktopCallbackRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/login": typeof LoginRoute;
  "/auth/desktop-callback": typeof AuthDesktopCallbackRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/login" | "/auth/desktop-callback";
  fileRoutesByTo: FileRoutesByTo;
  to: "/login" | "/auth/desktop-callback";
  id: "__root__" | "/login" | "/auth/desktop-callback";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute;
  AuthDesktopCallbackRoute: typeof AuthDesktopCallbackRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/desktop-callback": {
      id: "/auth/desktop-callback";
      path: "/auth/desktop-callback";
      fullPath: "/auth/desktop-callback";
      preLoaderRoute: typeof AuthDesktopCallbackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  AuthDesktopCallbackRoute: AuthDesktopCallbackRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
