export enum DatabaseErrorCode {
  ENTITY_NOT_FOUND = "DB_ENTITY_NOT_FOUND",
  CONNECTION_ERROR = "DB_CONNECTION_ERROR",
  QUERY_SYNTAX_ERROR = "DB_QUERY_SYNTAX_ERROR",
  UNIQUE_CONSTRAINT_ERROR = "DB_UNIQUE_CONSTRAINT_ERROR",
  FOREIGN_KEY_ERROR = "DB_FOREIGN_KEY_ERROR",
  TRANSACTION_ERROR = "DB_TRANSACTION_ERROR",
  AUTH_ERROR = "DB_AUTH_ERROR",
  PERMISSION_ERROR = "DB_PERMISSION_ERROR",
  TIMEOUT_ERROR = "DB_TIMEOUT_ERROR",
  BATCH_ERROR = "DB_BATCH_ERROR",
  INSERT_ERROR = "DB_INSERT_ERROR",
  UPDATE_ERROR = "DB_UPDATE_ERROR",
  DELETE_ERROR = "DB_DELETE_ERROR",
  NOT_NULL_ERROR = "DB_NOT_NULL_ERROR",
  UPSERT_ERROR = "DB_UPSERT_ERROR",
  DATA_LOADER_SAFETY_ERROR = "DB_DATA_LOADER_SAFETY_ERROR",
}

export enum GenericErrorCode {
  MULTIPLE_ERRORS = "MULTIPLE_ERRORS",
  RUNTIME_ERROR = "RUNTIME_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
}

export enum ApiErrorCode {
  VALIDATION_ERROR = "API_VALIDATION_ERROR",
  REQUEST_ERROR = "API_REQUEST_ERROR",
  RESPONSE_ERROR = "API_RESPONSE_ERROR",
  NETWORK_ERROR = "API_NETWORK_ERROR",
  PARSE_ERROR = "API_PARSE_ERROR",
  TIMEOUT_ERROR = "API_TIMEOUT_ERROR",
  SERVER_ERROR = "API_SERVER_ERROR",
  UNAUTHORIZED_ERROR = "API_UNAUTHORIZED_ERROR",
  FORBIDDEN_ERROR = "API_FORBIDDEN_ERROR",
  RATE_LIMIT_ERROR = "API_RATE_LIMIT_ERROR",
  RATE_LIMIT_RETRIES_EXCEEDED_ERROR = "API_RATE_LIMIT_RETRIES_EXCEEDED_ERROR",
  ENTITY_NOT_FOUND = "API_ENTITY_NOT_FOUND",
}

export type ErrorCode = DatabaseErrorCode | GenericErrorCode | ApiErrorCode;
