export const DISCORD_URL = "https://discord.gg/KSB2kzQWWE";
export const GITHUB_REPO = "https://github.com/Stormix/deadlock-modmanager";
export const DOWNLOAD_URL = `${GITHUB_REPO}/releases/latest`;
export const REDDIT_URL = "https://www.reddit.com/r/DeadlockModManager/";
export const X_URL = "https://x.com/DLModManager";
export const APP_NAME = "Deadlock Mod Manager";
export const COPYRIGHT = `© ${new Date().getFullYear()} ${APP_NAME}`;
export const SITE_URL = "https://deadlockmods.app";
export const STATUS_URL = "https://status.deadlockmods.app";
