{{- if .Values.resources.postgres }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Chart.Name }}
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: false
  instances: {{ .Values.resources.postgres.replicas }}

  # Faster failure detection and recovery
  startDelay: 300        # 5 min instead of default 1h - detect startup failures faster
  stopDelay: 300         # 5 min instead of default 30m - faster graceful shutdown
  switchoverDelay: 60    # 1 min instead of default 1h - faster manual switchovers
  maxStartupDelay: 300   # 5 min instead of default 1h - faster startup failure detection

  resources:
    requests:
      memory: {{ .Values.resources.postgres.memory }}
      cpu: {{ .Values.resources.postgres.cpu | quote }}
    limits:
      memory: {{ .Values.resources.postgres.memory }}
      cpu: {{ .Values.resources.postgres.cpu | quote }}
  storage:
    size: {{ .Values.resources.postgres.disk }}
    storageClass: hcloud-csi
  bootstrap:
    initdb:
      database: {{ .Chart.Name }}
      postInitSQL:
        - GRANT pg_create_subscription TO "{{ .Chart.Name }}";
        {{- if .Values.resources.postgres.extensions }}
        {{- range .Values.resources.postgres.extensions }}
        - CREATE EXTENSION IF NOT EXISTS {{ . }};
        {{- end }}
        {{- end }}
  postgresql:
    parameters:
      {{ .Values.resources.postgres.config | toYaml | nindent 6 }}
  monitoring:
    enablePodMonitor: true
  affinity:
    tolerations:
      - key: role
        value: database
        effect: NoSchedule
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/database
                operator: Exists
{{- end }}
