import { ModStatus, type LocalMod } from "../../src/types/mods";
export const fixtureMod = (modId: string, index: number): LocalMod => ({
  id: modId,
  remoteId: modId,
  name: modId,
  description: "E2E profile fixture",
  remoteUrl: "local://manual",
  category: "Skins",
  likes: 0,
  author: "E2E",
  downloadable: false,
  tags: [],
  images: [],
  hero: null,
  isAudio: false,
  isMap: false,
  audioUrl: null,
  downloadCount: 0,
  isNSFW: false,
  isObsolete: false,
  isBlacklisted: false,
  blacklistReason: null,
  blacklistedAt: null,
  blacklistedBy: null,
  filesUpdatedAt: null,
  overrides: null,
  createdAt: new Date(0),
  updatedAt: new Date(0),
  remoteAddedAt: new Date(0),
  remoteUpdatedAt: new Date(0),
  status: ModStatus.Installed,
  installedVpks: [`pak${String(index + 1).padStart(2, "0")}_dir.vpk`],
  installOrder: index,
  // These synthetic script archives contain no hero assets. Model them as
  // already indexed so unrelated background scans cannot race a test restart.
  detectedHero: null,
  usesCriticalPaths: false,
});
