name: Update AUR PKGBUILD for git package

on:
  push:
    branches:
      - main
    paths:
      - "distribution/aur/deadlock-modmanager-git/**"
  workflow_dispatch:

jobs:
  aur-git-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy PKGBUILD for deploy
        run: cp -r distribution/aur/deadlock-modmanager-git ./deadlock-modmanager-git

      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@2ac5a4c1d7035885d46b10e3193393be8460b6f1
        with:
          pkgname: deadlock-modmanager-git
          pkgbuild: deadlock-modmanager-git/PKGBUILD
          commit_username: GitHub Actions
          commit_email: github-actions@github.com
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Sync PKGBUILD from repo"
          updpkgsums: true
