name: Test Packages
env:
  NODE_VERSION: "24.8.0"

on:
  push:
    branches:
      - main
    paths:
      - "packages/**"
      - ".github/workflows/test.yml"
  pull_request:
    paths:
      - "packages/**"
      - ".github/workflows/test.yml"
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      kv-parser: ${{ steps.filter.outputs.kv-parser }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            kv-parser:
              - 'packages/kv-parser/**'

  test-kv-parser:
    name: Test kv-parser
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.kv-parser == 'true' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache-dependency-path: pnpm-lock.yaml

      - uses: pnpm/action-setup@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm --filter @deadlock-mods/kv-parser test

  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [test-kv-parser]
    if: always()
    steps:
      - name: Check test results
        run: |
          if [[ "${{ needs.test-kv-parser.result }}" == "failure" ]]; then
            echo "Test job failed"
            exit 1
          elif [[ "${{ needs.test-kv-parser.result }}" == "skipped" ]]; then
            echo "Test job was skipped - no changes detected"
            exit 0
          else
            echo "Test job passed"
            exit 0
          fi
